export const Users = [
    {
      id:1,
      profilePicture: "profile_pic/yoda.jpg",
      username: "Yoda",
    },
    {
      id:2,
      profilePicture: "profile_pic/john_wick.jpg",
      username: "John Wick",
    },
    {
      id:3,
      profilePicture: "profile_pic/mandalorian.jpg",
      username: "Mandalorian",
    },
    {
      id:4,
      profilePicture: "profile_pic/anakin.jpg",
      username: "Anakin Skywalker",
    },
    {
      id:5,
      profilePicture: "profile_pic/quigon.jpg",
      username: "Qui Gonn",
    },
    {
      id:6,
      profilePicture: "profile_pic/grogu.jpg",
      username: "Grogu",
    },
    {
      id:7,
      profilePicture: "profile_pic/Jon_Snow.png",
      username: "Jon Snow",
    },
    {
      id:8,
      profilePicture: "profile_pic/daenerys.jpg",
      username: "Daenerys Targareyan",
    },
    {
      id:9,
      profilePicture: "profile_pic/mormont.jpg",
      username: "Lady Mormont",
    },
    {
      id:10,
      profilePicture: "profile_pic/arya.jpg",
      username: "Arya Stark",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "posts/dawki.jpg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "posts/sevensister.jpg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "posts/root bridge.jpg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "posts/Wei-Sawdong.jpg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "posts/sevensister.jpg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "posts/dawki.jpg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "post/7.jpeg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "post/8.jpeg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "post/9.jpeg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "post/10.jpeg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];